l_russian:
  train_equipment_1: "Поезд"

  EQ_MOD_SLOT_locomotive_slot_TITLE: "Локомотив"
  EQ_MOD_CAT_locomotive_type_TITLE: "Локомотивы"
  great_war_locomotive: "Локомотив времён Великой войны"
  great_war_locomotive_desc: ""
  wartime_locomotive: "Военный локомотив"
  wartime_locomotive_desc: ""

  GER_great_war_locomotive: "Класс 18.4-5"
  GER_wartime_locomotive: "Тип DRB 52"
  SOV_great_war_locomotive: "Тип FD"
  SOV_wartime_locomotive: "Тип «L»"
  USA_great_war_locomotive: "Тип «Пенсильвания» I1s"
  USA_wartime_locomotive: "Тип USATC S160"
  JAP_great_war_locomotive: "Тип JNR D50"
  JAP_wartime_locomotive: "Тип JNR D52"
  ENG_great_war_locomotive: "LMS класса 8F"
  ENG_wartime_locomotive: "WD Austerity 2-8-0"
  FRA_great_war_locomotive: "141 B/C SNCF"
  FRA_wartime_locomotive: "141 P SNCF"
  ITA_great_war_locomotive: "FS Class 685"

  EQ_MOD_SLOT_vagon1_slot_TITLE: "Первый вагон"
  EQ_MOD_SLOT_vagon2_slot_TITLE: "Второй вагон"
  EQ_MOD_SLOT_vagon3_slot_TITLE: "Трейтий вагон"
  EQ_MOD_SLOT_vagon4_slot_TITLE: "Четвёртый вагон"
  EQ_MOD_SLOT_vagon5_slot_TITLE: "Пятый вагон"
  EQ_MOD_CAT_vagon_type_TITLE: "Грузовые вагоны"
	standart_vagon: "Гражданский вагон"
	standart_vagon_desc: ""
	armored_vagon: "Броневагон"
	armored_vagon_desc: ""
  EQ_MOD_CAT_aa_vagon_type_TITLE: "Вагоны ПВО"
  anti_air1_vagon: "ПВО Вагон"
  anti_air1_vagon_desc: ""
  anti_air2_vagon: "Улучшенный ПВО вагон"
  anti_air2_vagon_desc: ""
  anti_air3_vagon: "Продвинутый ПВО вагон"
  anti_air3_vagon_desc: ""

  wartime_train: "Военный упрощенный поезд"
  wartime_train_desc: "Упрощенный проект, в котором ради удешевления производства опущены многие детали, присущие обычным товарным поездам. Он точно так же уязвим, как и обычный поезд, но его проще заменить."
  GER_wartime_train: "Тип DRB 52"
  SOV_wartime_train: "Тип «L»"
  USA_wartime_train: "Тип USATC S160"
  JAP_wartime_train: "Тип JNR D52"
  ENG_wartime_train: "WD Austerity 2-8-0"
  FRA_wartime_train: "141 P SNCF"

  armored_train_desc: "Паровоз укрыт тяжелой броней, защищающей от вражеских атак. По грузоподъемности он равен другим поездам, но его выпуск стоит дороже."