l_english:
  train_equipment_1: "Train"

  EQ_MOD_SLOT_locomotive_slot_TITLE: "Locomotive"
  EQ_MOD_CAT_locomotive_type_TITLE: "Locomotives"
  great_war_locomotive: "Locomotive of the Great War"
  great_war_locomotive_desc: ""
  wartime_locomotive: "Wartime locomotive"
  wartime_locomotive_desc: ""


  GER_great_war_locomotive: "Class 18.4-5"
  GER_wartime_locomotive: "DRB 52 Class"
  SOV_great_war_locomotive: "FD Class"
  SOV_wartime_locomotive: "L Class"
  USA_great_war_locomotive: "Pennsylvania I1s Class"
  USA_wartime_locomotive: "USATC S160 Class"
  JAP_great_war_locomotive: "JNR D50 Class"
  JAP_wartime_locomotive: "JNR D52 Class"
  ENG_great_war_locomotive: "LMS Class 8F"
  ENG_wartime_locomotive: "WD Austerity 2-8-0"
  FRA_great_war_locomotive: "141 B/C SNCF"
  FRA_wartime_locomotive: "141 P SNCF"
  ITA_great_war_locomotive: "FS Class 685"

  EQ_MOD_SLOT_vagon1_slot_TITLE: "First train car"
  EQ_MOD_SLOT_vagon2_slot_TITLE: "Second train car"
  EQ_MOD_SLOT_vagon3_slot_TITLE: "Third train car"
  EQ_MOD_SLOT_vagon4_slot_TITLE: "Fourth train car"
  EQ_MOD_SLOT_vagon5_slot_TITLE: "Fifth train car"
  EQ_MOD_CAT_vagon_type_TITLE: "Freight train cars"
	standart_vagon: "Civilian train car"
	standart_vagon_desc: ""
	armored_vagon: "Armored train car"
	armored_vagon_desc: ""
  EQ_MOD_CAT_aa_vagon_type_TITLE: "Air defense train cars"
  anti_air1_vagon: "Air Defense train car"
  anti_air1_vagon_desc: ""
  anti_air2_vagon: "Improved Air Defense train car"
  anti_air2_vagon_desc: ""
  anti_air3_vagon: "Advanced Air Defense train car"
  anti_air3_vagon_desc: ""


  wartime_train: "War Austerity Train"
  wartime_train_desc: "A simplified design that ommits many features commonly found on regular freight trains for the sake of cheaper production. It is still every bit as vulnerable as a regular train, but can more easily be replaced."
  GER_wartime_train: "DRB 52 Class"
  SOV_wartime_train: "L Class"
  USA_wartime_train: "USATC S160 Class"
  JAP_wartime_train: "JNR D52 Class"
  ENG_wartime_train: "WD Austerity 2-8-0"
  FRA_wartime_train: "141 P SNCF"

  armored_train_desc: "A train engine encased in heavy armor to make it less vulnerable to enemy attack. It can carry as much cargo as any other design, but is more expensive to produce."